version: '3.8'

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    command: python3 client.py
    networks:
      mynet:
        ipv4_address: 172.28.0.2
    depends_on:
      - malicious_receiver
      - server
    volumes:
      - ./src:/app
      - ./certs:/certs
    environment:
      - PYTHONUNBUFFERED=1

  malicious_sender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: malicious_sender
    command: python3 malicious_sender.py
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./src:/app
      - ./certs:/certs
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - client

  malicious_receiver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: malicious_receiver
    command: python3 malicious_receiver.py
    ports:
      - "8443:8443"
    networks:
      mynet:
        ipv4_address: 172.28.0.3
    volumes:
      - ./src:/app
      - ./certs:/certs
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - server

  server: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    command: python3 server.py
    ports:
      - "443:443"
    networks:
      mynet:
        ipv4_address: 172.28.0.4
    volumes:
      - ./src:/app
      - ./certs:/certs
    environment:
      - PYTHONUNBUFFERED=1